### ISSUE TITLE
Search 1.0 end of life

### ISSUE THREAD

**Issue by digihash** [censys/censys-maltego#59]
Hi

Is it possible that the Maltego transform doesn't work anymore with the latest v2.0 API search? I get the following error when I try to use query a certificate in Maltego:
censys.common.exceptions.CensysSearchException: 200 (unknown): Search 1.0 has reached its End of Life. Please update your application to use the APIs available through Search 2.0. For more information visit https://support.censys.io/hc/en-us/articles/4404436837652-Search-1-0-and-IPv4-Banners-Deprecated-Resources-and-Available-Alternatives (from entity "example.net")

**Comment by thehappydinoa** [comment]
Hi @digihash,

I am in the process of upgrading various integration to V2. Thank you for reporting this.

**Comment by digihash** [comment]
Thanks @thehappydinoa, I guess this stays open until you upgraded everything. Let me know if you need help.

**Comment by thehappydinoa** [comment]
Hi there, I am in the process of updating this repo to point users towards the [Maltego Censys Integration](https://www.maltego.com/transform-hub/censys/). I am going to go ahead and close this issue for now. Thanks for your patience.
